(()=>{'use strict';
const C=document.querySelector('#game'),c=C.getContext('2d'),$=s=>document.querySelector(s),ui={screen:$('#screen'),start:$('#start'),copy:$('#screen-copy'),score:$('#score'),lead:$('#lead-score'),distance:$('#distance'),ink:$('#ink'),pause:$('#pause')};
const W=720,H=720,n='#0c1c37',paper='#f6efdf',pink='#ef5a62',mint='#aee8d2',yellow='#ffc94c',versions=['v2','v2-new','v2-new-fixed'],folders=['squid-racer-final','squid-racer-final-final','squid-racer-final-final-use-this'];let state='intro',score=0,metres=0,lives=3,p,items=[],keys={},last=0,audio,checkpoint=-1,notice='';
function reset(){score=metres=0;lives=3;checkpoint=-1;notice='';p={x:360,y:602,tilt:0,boost:100};items=[];for(let i=0;i<9;i++)add(-i*105);hud()}
function add(y=-30){let r=Math.random(),kind=r<.48?'crate':r<.76?'version':'jelly';items.push({x:100+Math.random()*520,y,kind,z:kind==='crate'?34:kind==='version'?27:18,spin:Math.random()*6,label:versions[Math.floor(Math.random()*versions.length)]})}
function hud(){let s=String(Math.max(0,score)).padStart(4,'0');ui.score.textContent=s;ui.lead.textContent=s;ui.distance.textContent=`${Math.floor(metres)}m`;ui.ink.textContent='● '.repeat(lives).trim()||'—'}
function beep(f=180,d=.06,type='square',v=.03){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function start(){audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();reset();state='play';ui.screen.classList.add('hide');ui.pause.hidden=false;beep(310,.09,'triangle',.06);last=0;requestAnimationFrame(loop)}
function end(title,copy,btn='RACE AGAIN →'){state='over';ui.screen.querySelector('h2').innerHTML=title;ui.copy.textContent=copy;ui.start.textContent=btn;ui.screen.classList.remove('hide');ui.pause.hidden=true}
function move(dt){let steer=(keys.left?-1:0)+(keys.right?1:0),boost=keys.boost&&p.boost>1;p.boost=Math.max(0,Math.min(100,p.boost+(boost?-1.2:.45)*dt));let v=(boost?6.8:3.6)*dt;p.x=Math.max(74,Math.min(W-74,p.x+steer*7.2*dt));p.tilt+=(steer*.22-p.tilt)*.16*dt;metres+=v*.095;score+=Math.max(0,Math.floor(dt*.05));items.forEach(x=>{x.y+=v;x.spin+=.03*dt;if(x.y>H+55){x.y=-55;x.x=100+Math.random()*520;let r=Math.random();x.kind=r<.48?'crate':r<.76?'version':'jelly';x.z=x.kind==='crate'?34:x.kind==='version'?27:18;x.label=versions[Math.floor(Math.random()*versions.length)]}});
for(const x of items)if(Math.abs(x.x-p.x)<x.z+28&&Math.abs(x.y-p.y)<x.z+34){x.y=H+100;if(x.kind==='version'){score+=125;notice=`VERSION FOUND: ${x.label}`;beep(640,.07,'sine',.05)}else if(x.kind==='crate'){lives--;notice='ROUTE OBSTRUCTED';beep(90,.16,'sawtooth',.07);if(!lives)end('THE ROUTE<br><em>ENDED.</em>','The folder remains extremely private.')}else{score+=25;beep(380,.06,'triangle',.035)}}
let next=Math.min(2,Math.floor(metres/300));if(next>checkpoint&&metres>=300){checkpoint=next;notice=`CHECKPOINT: ${folders[checkpoint]}`;beep(480,.12,'triangle',.05)}if(metres>=1000)end('UPLOAD<br><em>COMPLETE.</em>','PERSONAL CLOUD / squid-racer-final-final / SHARED WITH: 1 (FOLDER OWNER)');hud()}
function sea(){c.fillStyle='#266598';c.fillRect(0,0,W,H);c.fillStyle='#aee8d222';for(let i=0;i<26;i++){let x=(i*97+metres*1.8)%W,y=(i*131+metres*2.8)%H;c.beginPath();c.arc(x,y,2+i%4,0,7);c.fill()}c.fillStyle='#154a78';c.beginPath();c.moveTo(0,0);c.lineTo(80,0);c.lineTo(0,H);c.fill();c.beginPath();c.moveTo(W,0);c.lineTo(W-80,0);c.lineTo(W,H);c.fill();c.strokeStyle='#f6efdf66';c.lineWidth=4;c.setLineDash([16,18]);c.lineDashOffset=-metres*5;c.beginPath();c.moveTo(360,0);c.lineTo(360,H);c.stroke();c.setLineDash([])}
function thing(x){c.save();c.translate(x.x,x.y);if(x.kind==='crate'){c.rotate(x.spin*.02);c.fillStyle='#d89057';c.fillRect(-x.z,-x.z,x.z*2,x.z*2);c.strokeStyle=n;c.lineWidth=5;c.strokeRect(-x.z,-x.z,x.z*2,x.z*2);c.beginPath();c.moveTo(-x.z,-x.z);c.lineTo(x.z,x.z);c.moveTo(x.z,-x.z);c.lineTo(-x.z,x.z);c.stroke()}else if(x.kind==='version'){c.fillStyle=yellow;c.fillRect(-x.z*1.2,-16,x.z*2.4,32);c.strokeStyle=n;c.lineWidth=4;c.strokeRect(-x.z*1.2,-16,x.z*2.4,32);c.fillStyle=n;c.font='13px DM Mono';c.textAlign='center';c.textBaseline='middle';c.fillText(x.label,0,1)}else{c.fillStyle='#ee7481';c.beginPath();c.arc(0,0,x.z,0,7);c.fill();for(let i=-1;i<=1;i++){c.beginPath();c.moveTo(i*9,12);c.quadraticCurveTo(i*14,32,i*7,37);c.strokeStyle='#ee7481';c.lineWidth=6;c.stroke()}}c.restore()}
function squid(){c.save();c.translate(p.x,p.y);c.rotate(p.tilt);if(p.boost>1){c.fillStyle=yellow;c.beginPath();c.moveTo(0,32);c.lineTo(-18,70);c.lineTo(0,55);c.lineTo(18,70);c.closePath();c.fill()}c.fillStyle=pink;c.beginPath();c.ellipse(0,0,34,42,0,0,7);c.fill();c.fillStyle=paper;c.beginPath();c.arc(-12,-7,8,0,7);c.arc(12,-7,8,0,7);c.fill();c.fillStyle=n;c.beginPath();c.arc(-10,-6,3,0,7);c.arc(14,-6,3,0,7);c.fill();c.strokeStyle=pink;c.lineWidth=9;c.lineCap='round';for(let i=-2;i<=2;i++){c.beginPath();c.moveTo(i*10,29);c.quadraticCurveTo(i*13,49,i*7,58);c.stroke()}c.restore()}
function draw(){sea();items.sort((a,b)=>a.y-b.y).forEach(thing);squid();if(state==='play'){c.fillStyle=yellow;c.fillRect(16,H-25,120*p.boost/100,8);c.strokeStyle=n;c.strokeRect(16,H-25,120,8);if(notice){c.fillStyle=n+'dd';c.fillRect(90,18,540,38);c.fillStyle=paper;c.font='14px DM Mono';c.textAlign='center';c.textBaseline='middle';c.fillText(notice,360,37)}}}
function loop(t){if(state!=='play')return;let dt=Math.max(0,Math.min(2,(t-last)/16.67||1));last=t;move(dt);draw();requestAnimationFrame(loop)}
function pause(){if(state==='play'){state='pause';ui.screen.querySelector('h2').textContent='PAUSED';ui.copy.textContent='The current is waiting.';ui.start.textContent='CONTINUE →';ui.screen.classList.remove('hide')}else if(state==='pause'){state='play';ui.screen.classList.add('hide');last=0;requestAnimationFrame(loop)}}
let map={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'boost',' ':'boost'};addEventListener('keydown',e=>{if(map[e.key]){keys[map[e.key]]=true;e.preventDefault()}if((e.key==='p'||e.key==='P'||e.key==='Escape')&&state==='play')pause()});addEventListener('keyup',e=>{if(map[e.key])keys[map[e.key]]=false});document.querySelectorAll('[data-control]').forEach(b=>['pointerdown','pointerup','pointercancel','pointerleave'].forEach(v=>b.addEventListener(v,e=>{keys[b.dataset.control]=v==='pointerdown';e.preventDefault()})));C.addEventListener('pointermove',e=>{if(state==='play'&&e.buttons){let r=C.getBoundingClientRect();p.x=(e.clientX-r.left)/r.width*W}});ui.start.onclick=()=>state==='pause'?pause():start();ui.pause.onclick=pause;reset();draw();})();
